version: "3"

services:
  node_server_staging:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nodejs
    container_name: nandex_node_server_staging
    restart: on-failure
    env_file: .env
    environment:
      - NODE_ENV=staging
      - PORT=8080
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start
networks:
  app-network:
    driver: bridge
volumes:
  node_modules: