version: "3"

services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
#    image: nodejs
    container_name: nandex_node_server
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "8080:80"
    volumes:
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start
networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
