version: "3"

services:
  node_server_dev:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nodejs
    container_name: nandex_node_server_dev
    restart: on-failure
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules:
