module.exports = {
  WS_APP_ID_DEV: 1089,
  WS_APP_ID_STAGING: "YOUR_WS_APP_ID_STAGING",
  WS_APP_ID_PROD: 1089,

  STR_ENV_DEV: "development",
  STR_ENV_STAGING: "staging",
  STR_ENV_PROD: "production",

  MONGO_URI_DEV: `YOUR_MONGO_URI_DEVELOPMENT`,
  MONGO_URI_STAGING: `YOUR_MONGO_URI_STAGING`,
  MONGO_URI_PROD: `YOUR_MONGO_URI_PRODUCTION`,

  MYSQL_HOST_DEV: "192.168.1.147",
  MYSQL_USER_DEV: "root",
  MYSQL_PASS_DEV: "password",
  MYSQL_DATABASE_DEV: "nendx",
  MYSQL_PORT_DEV: "3306",

  MYSQL_HOST_STAGING: "YOUR_MYSQL_HOST_STAGING",
  MYSQL_USER_STAGING: "YOUR_MYSQL_USER_STAGING",
  MYSQL_PASS_STAGING: "YOUR_MYSQL_PASSWORD_STAGING",
  MYSQL_DATABASE_STAGING: "YOUR_MYSQL_DATABASE_STAGING",
  MYSQL_PORT_STAGING: "YOUR_MYSQL_PORT_STAGING",

  MYSQL_HOST_PROD: "itempire.cvqgeqg55s3t.us-east-2.rds.amazonaws.com",
  MYSQL_USER_PROD: "nandex",
  MYSQL_PASS_PROD: "MhrRC84jWjMEsVDS",
  MYSQL_DATABASE_PROD: "nandex",
  MYSQL_PORT_PROD: "3306",

  PUSHER_APP_ID_DEV: "1223392",
  PUSHER_APP_KEY_DEV: "4095102f6656ab012d5c",
  PUSHER_APP_SECRET_DEV: "623a2a4419e88f5d6f00",
  PUSHER_APP_CLUSTER_DEV: "ap2",

  PUSHER_APP_ID_STAGING: "YOUR_PUSHER_APP_ID_STAGING",
  PUSHER_APP_KEY_STAGING: "YOUR_PUSHER_APP_KEY_STAGING",
  PUSHER_APP_SECRET_STAGING: "YOUR_PUSHER_APP_SECRETWORD_STAGING",
  PUSHER_APP_CLUSTER_STAGING: "YOUR_PUSHER_APP_CLUSTER_STAGING",
  
  PUSHER_APP_ID_PROD: "YOUR_PUSHER_APP_ID_PRODUCTION",
  PUSHER_APP_KEY_PROD: "YOUR_PUSHER_APP_KEY_PRODUCTION",
  PUSHER_APP_SECRET_PROD: "YOUR_PUSHER_APP_SECRETWORD_PRODUCTION",
  PUSHER_APP_CLUSTER_PROD: "YOUR_PUSHER_APP_CLUSTER_PRODUCTION",
};
